### ISSUE TITLE
fluidsynth: if Preference.SF2Soundfont not set, then segfault: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed

### ISSUE THREAD

**Issue by dufresnep** [Wargus/stratagus#304]
I kind of try to use 'recent' versions of Stratagus to run Aleona's Tales (2012 version): AT-RT2.
This does something like:
```
paul@Bagotteville:~/Documents/stratagus-master-builds/build$ ./stratagus -d /home/paul/Downloads/AT-R2 
Can't open file 'preferences.lua': No such file or directory
Can't open file `orc/units/dentarg/acknowledgement/1.wav'
Can't open file `orc/units/dentarg/acknowledgement/1.wav'
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
fluidsynth: error: Unknown integer parameter 'synth.parallel-render'
fluidsynth: error: Unknown string setting 'synth-midi-bank-select'
fluidsynth: error: Unknown integer parameter 'synth.synth-polyphony'
ici 1ici2fluidsynth: error: fluid_sfloader_load(): Failed to open '/home/paul/.stratagus/wc2/': File is not regular, refusing to open it.
fluidsynth: error: Unable to open file '/home/paul/.stratagus/wc2/'

** (process:78463): CRITICAL **: 20:52:47.021: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed
Segmentation fault (core dumped)
paul@Bagotteville:~/Documents/stratagus-master-builds/build$ 
```
And:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6c6c91d in ipatch_dls2_inst_first () from /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
(gdb) bt
#0  0x00007ffff6c6c91d in ipatch_dls2_inst_first () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#1  0x00007ffff6c70b7a in  () at /lib/x86_64-linux-gnu/libinstpatch-1.0.so.2
#2  0x00007ffff6bf7d0e in g_object_unref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff7d8ceb5 in  () at /lib/x86_64-linux-gnu/libfluidsynth.so.2
#4  0x00007ffff7d8d3be in  () at /lib/x86_64-linux-gnu/libfluidsynth.so.2
#5  0x00007ffff7dac5c5 in fluid_synth_sfload () at /lib/x86_64-linux-gnu/libfluidsynth.so.2
#6  0x00005555557bc06a in InitFluidSynth() ()
#7  0x00005555557bc1e0 in LoadFluidSynth(char const*, int) ()
#8  0x00005555557c5914 in LoadSample(char const*, _play_audio_flags_) ()
#9  0x00005555557c5983 in LoadSample(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x00005555557c0d0e in RegisterSound(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#11 0x00005555557c3170 in MakeSound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#12 0x00005555557be7d6 in CclMakeSound(lua_State*) ()
#13 0x00007ffff7f7fbfc in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#14 0x00007ffff7f8aac5 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#15 0x00007ffff7f8019d in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#16 0x00007ffff7f7f483 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#17 0x00007ffff7f80341 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#18 0x00007ffff7f7be8c in lua_pcall () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#19 0x00005555557e4d58 in LuaCall(int, int, bool) ()
#20 0x00005555557e50bb in LuaLoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#21 0x00005555557e5290 in CclLoad(lua_State*) ()
#22 0x00007ffff7f7fbfc in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#23 0x00007ffff7f8aac5 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#24 0x00007ffff7f8019d in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#25 0x00007ffff7f7f483 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#26 0x00007ffff7f80341 in  () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#27 0x00007ffff7f7be8c in lua_pcall () at /lib/x86_64-linux-gnu/liblua5.1.so.0
#28 0x00005555557e4d58 in LuaCall(int, int, bool) ()
#29 0x00005555557e50bb in LuaLoadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#30 0x00005555557ef22b in LoadCcl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#31 0x00005555557fbc9f in stratagusMain(int, char**) ()
#32 0x00005555557ddef1 in main ()
(gdb) 
```
I think this happens in fluidsynth.cpp, in int InitFluidSynth(), near:
	std::string sf2Path = LibraryFileName(Preference.SF2Soundfont.c_str());
    if (fluid_synth_sfload(FluidSynthesizer.Synth, sf2Path.c_str(), 1) == -1) {
when Preference.SF2Soundfont is not set... Alexona's Tales does use an old version (2.x) that does not use preferences.lua

I believe that variable is a file on a instrument bank that is supposed to allow to transform midi files (Aleona's Tales does not seems to use that but the engine seems to allows that) to transform in raw audio for integrated audio not supporting midi... I think.

**Comment by timfel** [comment]
Fluidsynth has been removed from the engine. There's no release, yet, but you can try to build from master. We're now using the SDL2 midi support directly

**Comment by dufresnep** [comment]
Good! Great move!

I built from master.
And now, after commenting out 2 lines linked to OpenGL, I feel like getting real errors linked to the evolution of stratagus:
```
/home/paul/Documents/stratagus-master/src/unit/script_unittype.cpp:1135: CclDefineUnitType: Unsupported tag: CanGroundAttack
Unsupported tag: CanGroundAttack
stack traceback:
	[C]: in function 'DefineUnitType'
	[string "scripts/human/units.lua"]:154: in main chunk
	[C]: in function 'Load'
	[string "scripts/units.lua"]:499: in main chunk
	[C]: in function 'Load'
	[string "scripts/stratagus.lua"]:367: in main chunk
paul@Bagotteville:~/Downloads/AT-R2$ 
```

**Comment by Kintobor** [comment]
The last version I know which worked with AT was Wargus 2.3, which included it.

Going off memory there are two script changes in AT from Wargus. When the flag is changed from Wargus to AT, a single briefing graphic definition is changes, and the file /scripts/cannoo/override.lua is loaded.
