### ISSUE TITLE
segmentation fault occurs after loading a save file

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#49]
I'm having this crash happen when I load a save file for a game that was working without fault before I saved, exited, and loaded it. Save file and backtrace attached.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-10-04T11:38:39Z
 * owner: tent405
 * assignee: iddqd-mail
 * the launchpad url was https://bugs.launchpad.net/bugs/867398

**Comment by timfel** [comment]
(by tent405)

**Comment by timfel** [comment]
(by tent405)
save file which caused the segfault

**Comment by timfel** [comment]
(by ayzen-quwe)
Have the same problem. Additionally segfaluts appears after 5-8 minutes of play.

**Comment by timfel** [comment]
(by ayzen-quwe)
Mine save file which causes segfault.

**Comment by timfel** [comment]
(by ayzen-quwe)
I noticed that these segfaults happens only in Human compaign.

**Comment by timfel** [comment]
(by viniciusfs)
I have this problem with save file from both Human and Orc campaigns. Impossible to play the game without saves.

**Comment by timfel** [comment]
(by lists-jjorge)
Same bug here. I tried to get a backtrace :

#0  0x00007ffff5e29190 in std::string::assign(std::string const&) () from /lib64/libstdc++.so.6
#1  0x0000000000477b12 in operator= (__str=<error reading variable: Cannot access memory at address 0x18>, this=0x244aea0)
    at /usr/include/c++/4.8.2/bits/basic_string.h:547
#2  CclDefineAiPlayer (l=<optimized out>) at /usr/src/debug/stratagus_2.2.7.orig/src/ai/script_ai.cpp:1182
#3  0x00007ffff7bbc288 in luaD_precall () from /lib64/liblua.so.5.1
#4  0x00007ffff7bc69cf in luaV_execute () from /lib64/liblua.so.5.1
#5  0x00007ffff7bbc6cd in luaD_call () from /lib64/liblua.so.5.1
#6  0x00007ffff7bbb9bb in luaD_rawrunprotected () from /lib64/liblua.so.5.1
#7  0x00007ffff7bbc85a in luaD_pcall () from /lib64/liblua.so.5.1
#8  0x00007ffff7bb861d in lua_pcall () from /lib64/liblua.so.5.1
#9  0x00000000004e78b8 in LuaCall (narg=narg@entry=0, clear=clear@entry=1, exitOnError=exitOnError@entry=true)
    at /usr/src/debug/stratagus_2.2.7.orig/src/stratagus/script.cpp:162
#10 0x00000000004e79af in LuaLoadFile (file="/home/jose/.stratagus/wc2/save/game.sav.gz")
    at /usr/src/debug/stratagus_2.2.7.orig/src/stratagus/script.cpp:230
#11 0x000000000048a74b in LoadGame (filename="/home/jose/.stratagus/wc2/save/game.sav.gz")
    at /usr/src/debug/stratagus_2.2.7.orig/src/game/loadgame.cpp:213
#12 0x000000000048f992 in StartSavedGame (filename="~save/game.sav.gz") at /usr/src/debug/stratagus_2.2.7.orig/src/game/savegame.cpp:198

**Comment by timfel** [comment]
(by iddqd-mail)
Have you used the latest versions of stratagus and wargus from trunk?

**Comment by timfel** [comment]
(by tent405)
I reported this bug two years ago. 
I no longer have any interest in it, so I'm muting it. 
But it may still be a valid bug, according to jjorge.

**Comment by timfel** [comment]
(by myself600)
This bug still occurs, rendering the game very hard to play. I'm using the latest version from Stratagus PPA, playing the Orc campaign from ToD on Trisquel 6.0 64-bit (Ubuntu 12.04 based). The saved games are unloadable after a certain time of gameplay, so early saved games does load correctly and only the later ones are causing segfault.

**Comment by timfel** [comment]
(by iddqd-mail)
Try to use latest trunk versions of Stratagus and Wargus, not these that are on PPA (they are really outdated). I can't reproduce the bug in later versions, so I suggest it was fixed

**Comment by timfel** [comment]
(by myself600)
Tried, but this results in another issue. Rather than ending with segfault, the loading time is linearly dependent on the gameplay, so for example, a 15 minutes of saved gameplay will result in circa the same amount of loading time. There are other issues though I have not experienced in the stable version, but that's for another topic.

**Comment by timfel** [comment]
(by iddqd-mail)
Fixed that long loading in rev.8896, try it out.
